name: Feature request
description: Request an enhancement for movelang
labels: [enhancement]
body:

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        >
        > Before requesting:
        > 
        > - Search [existing issues](https://github.com/fishman/movelang.nvim/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).
        > - If you are reporting a bug, please use the [correct form](https://github.com/fishman/movelang.nvim/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml).

  - type: textarea
    attributes:
      label: "Feature description"
    validations:
      required: true
